<?php

/**
* @name        JMY CMS
* @link        http://jmy.su/
* @copyright   Copyright (C) 2012-2015 JMY LTD
* @license     LICENSE.txt (see attached file)
* @version     VERSION.txt (see attached file)
* @author      Komarov Ivan
* @edit 	   03.02.2015
*/

define('_GLOBAL', 'The basic configurations');
define('_GLOBAL_METATAGS', 'Adjustment of meta-tags');
define('_GLOBAL_METATAGS_URLT', 'URL a site');
define('_GLOBAL_METATAGS_URLD', 'The main adjustment of system the address with http:// without / in the end');
define('_GLOBAL_METATAGS_NAMET', 'Site name');
define('_GLOBAL_METATAGS_NAMED', 'It will be constantly displayed in a meta-tag &lt;title&gt;&lt;/title&gt;');
define('_GLOBAL_METATAGS_DESCRIPTIONT', 'The site description');
define('_GLOBAL_METATAGS_DESCRIPTIOND', 'It will be displayed in a meta-tag description');
define('_GLOBAL_METATAGS_SLOGANT', 'Site slogan');
define('_GLOBAL_METATAGS_SLOGAND', 'It will be displayed in a meta-tag &lt;title&gt;&lt;/title&gt; near to "the site Name"');
define('_GLOBAL_METATAGS_KEYWORDST', 'Keywords');
define('_GLOBAL_METATAGS_KEYWORDSD', 'Think before filling a field. It serves for optimisation of a site for search engines!');
define('_GLOBAL_METATAGS_DIVIDERT', 'Separator');
define('_GLOBAL_METATAGS_DIVIDERD', 'The separator serves for division of headings in &lt;title&gt;&lt;/title&gt; to enter with blanks [blank|blank]');
define('_GLOBAL_METATAGS_CHARSETT', 'The site coding');
define('_GLOBAL_METATAGS_CHARSETD', 'If you do not know that it for a field, do not change');
define('_GLOBAL_METATAGS_MAINMODULET', 'The module on the main');
define('_GLOBAL_METATAGS_MAINMODULED', 'Name of a folder of the module which should be displayed on the main');
define('_GLOBAL_METATAGS_LANGT', 'Site language');
define('_GLOBAL_METATAGS_LANGD', 'Choose site language');
define('_GLOBAL_METATAGS_MULTILANGT', 'Multilanguage');
define('_GLOBAL_METATAGS_MULTILANGD', 'Whether your site will support some languages?');
define('_GLOBAL_OTHER', 'Other');
define('_GLOBAL_OTHER_ENGINEVERSIONT', 'The system version');
define('_GLOBAL_OTHER_ENGINEVERSIOND', 'The system version');
define('_GLOBAL_OTHER_UNIQKEY', 'Unique code of a site');
define('_GLOBAL_OTHER_UNIQKEYD', 'The given code protects your site from the breaking, each site has the unique code, therefore to guess it it is impossible.');
define('_GLOBAL_OTHER_ENGINECREATORST', 'Developers of system');
define('_GLOBAL_OTHER_ENGINECREATORSD', 'Know by sight :)');
define('_GLOBAL_OTHER_TIMEZONET', 'Time belt');
define('_GLOBAL_OTHER_TIMEZONED', 'Choose GMT a belt for your site. All dates on a site will be formatted on its options.');
define('_GLOBAL_OTHER_TPLT', 'Site temlate');
define('_GLOBAL_OTHER_TPLD', 'Choose from the list the offered themes of registration for your site');
define('_GLOBAL_OTHER_TPL_MOBI', 'To include a separate template for smart phones');
define('_GLOBAL_OTHER_TPL_MOBI_DESC', 'If the user comes from the mobile device the template will be loaded from a folder usr/tpl/smartphone');
define('_GLOBAL_OTHER_TPL_CHANGE', 'Allow changing the template online');
define('_GLOBAL_OTHER_TPL_CHANGE_DESC', 'If you use multiple templates on the site, then you can allow visitors to switch between them');
define('_GLOBAL_OTHER_DBTYPET', 'Database type');
define('_GLOBAL_OTHER_DBTYPED', 'Choose from the list database type which it is used at you on the server');
define('_GLOBAL_OTHER_IMAGEEFFECTT', 'Effect of pictures');
define('_GLOBAL_OTHER_IMAGEEFFECTD', 'Choose from the list effect which will be used at disclosing of pictures.');
define('_GLOBAL_OTHER_SUPPORT_MAILT', 'E-Mail for communication');
define('_GLOBAL_OTHER_SUPPORT_MAILD', 'The given electronic address will be used in feedback functions');
define('_GLOBAL_GLOBALFUNC', 'Global functions of system');
define('_GLOBAL_GLOBALFUNC_GZIPT', 'To activate compression G-Zip?');
define('_GLOBAL_GLOBALFUNC_GZIPD', 'Compression will allow to save the traffic of your users, but do not abuse the given function on large portals.');
define('_GLOBAL_GLOBALFUNC_OFFT', 'To close a site on preventive maintenance');
define('_GLOBAL_GLOBALFUNC_OFFD', 'If your site is not completed yet close it on preventive maintenance and continue work');
define('_GLOBAL_GLOBALFUNC_OFF_TEXTT', 'The text at preventive maintenance');
define('_GLOBAL_GLOBALFUNC_OFF_TEXTD', 'The text which will be displayed at a preventive mode');
define('_GLOBAL_GLOBALFUNC_FULLAJAXT', 'Activate FullAjax?');
define('_GLOBAL_GLOBALFUNC_FULLAJAXD', 'BETA MODE.');
define('_GLOBAL_GLOBALFUNC_REFFERT', 'Consider reffer?');
define('_GLOBAL_GLOBALFUNC_REFFERD', 'At inclusion the system will conduct broad gulls of calling on a site from search engines.');
define('_GLOBAL_GLOBALFUNC_CACHET', 'Activate cache?');
define('_GLOBAL_GLOBALFUNC_CACHED', 'If at you you can activate the big portal cache separate parts of a site');
define('_GLOBAL_GLOBALFUNC_DBCACHET', 'To activate cache databases?');
define('_GLOBAL_GLOBALFUNC_DBCACHED', 'If at you the big portal you can activate cache databases.');
define('_GLOBAL_GLOBALFUNC_COMMENTST', 'To activate system of comments');
define('_GLOBAL_GLOBALFUNC_COMMENTSD', 'If you do not use comments on a site, disconnect them.');
define('_GLOBAL_GLOBALFUNC_MOD_REWRITET', 'Activate URL');
define('_GLOBAL_GLOBALFUNC_MOD_REWRITED', 'Switching-off cheloveko-clear URL will lead to loading increase on a site');
define('_GLOBAL_GLOBALFUNC_COUNTERT', 'To count up visitors?');
define('_GLOBAL_GLOBALFUNC_COUNTERD', 'In system there is a built in function of calculation of visitings. You can deduce it by means of the block.');
define('_GLOBAL_GLOBALFUNC_PLUGINT', 'To include an integration class?');
define('_GLOBAL_GLOBALFUNC_PLUGIND', 'If to include this option in a profile the class plugin which can be copied as integration to standard functions will be connected.');
define('_SECURITY', 'Options of safety of system');
define('_SECURITY_INFORMATION', 'To fields <i> Forbidden nicks, the Forbidden e-mails, the Stop words Blocked IP </i> it is possible to apply a following rule: <br/> * - <u> any symbols, whether it be figures, letters or signs </u> <br/> % - <u> only 1 any symbol! </u> <br/> <b> the Example: </b> <br/> % laed* - will block slaed, laed, slaed_cms and so on.');
define('_SECURITY_FILTER', 'Filtration of the data');
define('_SECURITY_FILTER_XNUMST', 'Confidential code');
define('_SECURITY_FILTER_XNUMSD', 'Enter a code a consisting maximum from 6 symbols! It will be used for an encryption of the data.');
define('_SECURITY_FILTER_STOPNICKT', 'Forbidden nicks');
define('_SECURITY_FILTER_STOPNICKD', 'The given option will allow you to forbid registration under defined nicks. <br/>To enter them follows through a comma(,).');
define('_SECURITY_FILTER_STOPMAILST', 'Forbidden e-mails');
define('_SECURITY_FILTER_STOPMAILSD', 'The option will not allow to use an e-mail from the list at registration, оставлении comments and also to use for the form return communications. An input format through a comma(,).');
define('_SECURITY_FILTER_STOPWORDST', 'Stop words');
define('_SECURITY_FILTER_STOPWORDSD', 'Stop words serve for anticipation of acceptable expressions in site publications.');
define('_SECURITY_FILTER_STOPREPLACET', 'Replacement of stop words');
define('_SECURITY_FILTER_STOPREPLACED', 'All stop words from the list will be replaced with the given value.<br /> Leave empty and words will be simply cut out.');
define('_SECURITY_FILTER_ALLOWHTMLT', 'Resolved HTML tags');
define('_SECURITY_FILTER_ALLOWHTMLD', 'List through a comma теги which can be used on a site.');
define('_SECURITY_IPS', 'Blocking on IP');
define('_SECURITY_IPS_BANIPT', 'Blocked IP');
define('_SECURITY_IPS_BANIPD', 'If at calling on a site it will be found out that IP the user is in the given list access to a site to it, will be limited.');
define('_SECURITY_IPS_BANIPMESSAGET', 'The message at blocking');
define('_SECURITY_IPS_BANIPMESSAGED', 'The message which will be displayed at conflict IP.');
define('_SECURITY_SWITCH', 'To include captcha?');
define('_SECURITY_SWITCH_DESC', 'To activate check of spams-boats?');
define('_SECURITY_CAPTCHA', 'Adjustment of(Captcha)');
define('_SECURITY_RECAPTHA', 'To use ReCaptcha?');
define('_SECURITY_RECAPTHA_DESC', 'To use ReCaptcha?');
define('_SECURITY_RECAPTHA_PUBLIC', 'Public key ReCaptcha');
define('_SECURITY_RECAPTHA_PUBLIC_DESC', 'Receive a public key you can under the reference: http://www.google.com/recaptcha');
define('_SECURITY_RECAPTHA_PRIVATE', 'Private key ReCaptcha');
define('_SECURITY_RECAPTHA_PRIVATE_DESC', 'Receive a private key you can under the reference: http://www.google.com/recaptcha');
define('_SECURITY_CAPTCHA_CAPTCHA_WIDTHT', 'Width captcha');
define('_SECURITY_CAPTCHA_CAPTCHA_WIDTHD', 'Width in pixels');
define('_SECURITY_CAPTCHA_CAPTCHA_HEIGHTT', 'Height captcha');
define('_SECURITY_CAPTCHA_CAPTCHA_HEIGHTD', 'Height in pixels');
define('_SECURITY_CAPTCHA_CAPTCHA_LENGHTT', 'Quantity of signs');
define('_SECURITY_CAPTCHA_CAPTCHA_LENGHTD', 'At exhibiting of quantity of signs, будте are attentive, do not forget that the width and image height depends on quantity of signs!');
define('_FILES', 'Management of files');
define('_FILES_FILE', 'The general parametres');
define('_FILES_FILE_IMGFORMATST', 'Formats the image');
define('_FILES_FILE_IMGFORMATSD', 'List through a comma those formats which in system should be used as the image');
define('_FILES_FILE_ATTACHFORMATST', 'Formats attachment');
define('_FILES_FILE_ATTACHFORMATSD', 'Formats of files which in system will be loaded as attachment (files) and will be accessible to downloading in the form of the reference.');
define('_FILES_FILE_MAX_SIZET', 'The maximum size');
define('_FILES_FILE_MAX_SIZED', 'The maximum size of loaded files in bytes');
define('_FILES_THUMB', 'Creation of previews (bedside tables)');
define('_FILES_THUMB_THUMB_WIDTHT', 'Width of a preview');
define('_FILES_THUMB_THUMB_WIDTHD', 'The maximum width of the image, at excess, a picture will be automatically reduced. Width in px');
define('_FILES_THUMB_QUALITYT', 'Quality of a preview');
define('_FILES_THUMB_QUALITYD', 'The number is underlined in %. Than less figure that will weigh less preview.');
define('_FILES_WATERMARK', 'Watermark');
define('_FILES_WATERMARK_WATERMARKT', 'To include watermark?');
define('_FILES_WATERMARK_WATERMARKD', 'At the included option on all pictures loaded through site services the watermark will be imposed.');
define('_FILES_WATERMARK_WATERMARK_TEXTT', 'The watermark text');
define('_FILES_WATERMARK_WATERMARK_TEXTD', 'If the picture ватермарка is not specified the specified text is imposed. It is recommended only with GD2');
define('_FILES_WATERMARK_WATERMARK_IMAGET', 'Watermark picture');
define('_FILES_WATERMARK_WATERMARK_IMAGED', 'To impose a picture on the image, specify its address here. The Watermark should be in format PNG and it is desirable with 24 bit alpha the channel.');
define('_FILES_WATERMARK_WATERMARK_VALIGNT', 'Arrangement on a vertical');
define('_FILES_WATERMARK_WATERMARK_VALIGND', 'Choose a watermark arrangement in a vertical plane.');
define('_FILES_WATERMARK_WATERMARK_HALIGNT', 'Arrangement horizontal');
define('_FILES_WATERMARK_WATERMARK_HALIGND', 'Choose a watermark arrangement in a horizontal plane.');
define('_ADMIN', 'Adjustment of the administrative panel');
define('_ADMIN_MAIN', 'The general parametres');
define('_ADMIN_MAIN_NUMT', 'Quantity on page');
define('_ADMIN_MAIN_NUMD', 'To display what quantity of a content on page in sections the administrator of the panel.');
define('_ADMIN_MAIN_IPACCESST', 'Access on IP');
define('_ADMIN_MAIN_IPACCESSD', 'Restriction of access to the administrative panel on IP. If empty - access by all.');
define('_ADMIN_MAIN_IPACCESS_HELP', '<br />Example (the beginning range|end a range): <br /><i>192.168.0.0|192.168.255.255<br />83.15.0.0|84.20.255.255</i><br />Each group of ranges since a new line.');
define('_ADMIN_HTMLEDITORT', 'To use HTML the editor');
define('_ADMIN_HTMLEDITORD', 'To use HTML the editor at addition of posts in the administrative panel');
define('_ADMIN_MAIN_SESSIONST', 'To activate sessions');
define('_ADMIN_MAIN_SESSIONSD', 'If the given parametre is included, the input in the control panel will be made each time separately at browser reboot.');
define('_ADMIN_MAIN_BART', 'Information bar');
define('_ADMIN_MAIN_BARD', 'To activate an information bar, for fast navigation on site pages?');
define('_USERC', 'Adjustment of the user part');
define('_USER_MAIN', 'Groups');
define('_USER_MAIN_GUESTGROUPT', 'Group of visitors');
define('_USER_MAIN_GUESTGROUPD', 'Choose group to which will be concerns visitors');
define('_USER_MAIN_BOTGROUPT', 'Group of boats');
define('_USER_MAIN_BOTGROUPD', 'Choose group to which will be concerns search boats');
define('_USER_MAIN_BANGROUPT', 'Group banneds');
define('_USER_MAIN_BANGROUPD', 'Choose group to which will be concerns banned users');
define('_USER_COUNT_POINTST', 'Counting of points');
define('_USER_COUNT_POINTSD', 'To conduct calculation of "points" of users, at performance of certain actions on a site?');
define('_USER_AVATAR', 'Avatar adjustment');
define('_USER_AVATAR_NOAVATART', 'The picture "Is not present an avatar"');
define('_USER_AVATAR_NOAVATARD', 'Specify the address of a picture which will be at the user without an avatar.');
define('_USER_AVATAR_AVATAR_LOADT', 'To load avatars');
define('_USER_AVATAR_AVATAR_LOADD', 'Option of loading of avatars on the server');
define('_USER_AVATAR_AVATAR_WIDTHT', 'Width of an avatar');
define('_USER_AVATAR_AVATAR_WIDTHD', 'The maximum width of an avatar in px');
define('_USER_AVATAR_AVATAR_HEIGHTT', 'Avatar height');
define('_USER_AVATAR_AVATAR_HEIGHTD', 'The maximum height of an avatar in px');
define('_USER_AVATAR_AVATAR_SIZET', 'The maximum size of an avatar');
define('_USER_AVATAR_AVATAR_SIZED', 'Maximum the size of an avatar in bytes');
define('_USER_REGISTER', 'Registration');
define('_USER_REGISTER_WITH_ACTIVATET', 'Registration with activation?');
define('_USER_REGISTER_WITH_ACTIVATED', 'After registration to send on mail of the user the letter with acknowledgement?');
define('_USER_BBEDITOR', 'Editors');
define('_USER_BBEDITOR_ACTIVEFLASHT', 'To resolve addition flash');
define('_USER_BBEDITOR_ACTIVEFLASHD', 'Whether you allow to use a tag [flash][/flash] in the user bb-editor?');
define('_USER_BBEDITOR_ACTIVEVIDEOT', 'To resolve video of references');
define('_USER_BBEDITOR_ACTIVEVIDEOD', 'Whether you allow to use a tag [video][/video] in the user bb-editor?');
define('_USER_BBEDITOR_ACTIVEAUDIOT', 'To resolve audio of references');
define('_USER_BBEDITOR_ACTIVEAUDIOD', 'Whether you allow to use a tag [audio][/audio] in the user bb-editor?');
define('_USER_BBEDITOR_ACTIVEATTACHT', 'To resolve addition of files');
define('_USER_BBEDITOR_ACTIVEATTACHD', 'Whether you allow to use loading of files by users of a site?');
define('_USER_BBEDITOR_HIGHLGIHTT', 'To highlight syntax of a code?');
define('_USER_BBEDITOR_HIGHLGIHTD', 'To use illumination of syntax for a tag [code=...][/code]?');
define('_USER_BBEDITOR_EDITORT', 'What editor to use');
define('_USER_BBEDITOR_EDITORD', 'Choose what editor it will be accessible to users to work');
define('_USER_BBEDITOR_BBVIZT', 'Visualisation BB of the editor');
define('_USER_BBEDITOR_BBVIZD', 'The option gives possibility to users at once to see result of parsing of the text in the editor');
define('_USER_COMMENTS', 'Comments');
define('_USER_COMMENTS_COMMENTOFTENT', 'Time between comments');
define('_USER_COMMENTS_COMMENTOFTEND', 'Establish a time interval in seconds through which will well add comments. To disconnect the given option establish 0.');
define('_USER_COMMENTS_COMMTREET', 'Treelike comments');
define('_USER_COMMENTS_COMMTREED', 'Function will allow users to answer comments, creating similarity of a tree.');
define('_USER_COMMENTS_COMMEDTEXT', 'Mark for editing comments');
define('_USER_COMMENTS_COMMEDTEXTD', '{user} - The user name, {date} - editing date. Leave empty if want to disconnect the given function.');
define('_USER_COMMENTS_COMMMODERATE', 'Premoderation of comments');
define('_USER_COMMENTS_COMMMODERATED', 'If to include the given function you will be obliged moderation each comment which will be added to you on a site.');
define('_USER_COMMENTS_SUBSCRIBET', 'Subscription to comments');
define('_USER_COMMENTS_SUBSCRIBED', 'To allow users to subscribe for comments which will be sent to them on an e-mail the address.');
define('_USER_COMMENTS_SIGNATURET', 'Signature template');
define('_USER_COMMENTS_SIGNATURED', 'Edit a template of the signature of the user for system comments. If the given field is empty, the signature will not be deduced!');
define('_USER_OTHER', 'Other');
define('_USER_OTHER_PMSHOWNT', 'Messages about new PM');
define('_USER_OTHER_PMSHOWND', 'To show messages at reception new PM to the user. +1 inquiry to a database');
define('_USER_OTHER_ISBANT', 'To resolve ban users?');
define('_USER_OTHER_ISBAND', 'If you consider that will never apply ban, disconnect the given function');
define('_USER_OTHER_USERWALLT', 'To activate a wall of the user?');
define('_USER_OTHER_USERWALLD', 'The wall allows users to leave the message and opinions in site profiles.');
define('_USER_OTHER_USERWALLNUMT', 'Wall records on one page');
define('_USER_OTHER_USERWALLNUMD', 'How many records of the user to display on one page');
define('_USER_OTHER_USERFRIENDST', 'Friendship between users');
define('_USER_OTHER_USERFRIENDSD', 'Expands possibilities of interaction of users among themselves');
define('_USER_OTHER_USERGUESTST', 'To consider visitors of the user');
define('_USER_OTHER_USERGUESTSD', 'The system will write down and deduce users which visited page');
define('_USER_OTHER_READBLOGT', 'The signature on blogs');
define('_USER_OTHER_READBLOGD', 'To deduce blogs on which the user is signed?');
define('_FULLAJAX', 'System adjustment FullAjax');
define('_FULLAJAX_MAIN', 'The basic options');
define('_FULLAJAX_MAIN_LOADERT', 'ID the loader');
define('_FULLAJAX_MAIN_LOADERD', 'Specify ID a layer of the loader which will be seemed/disappear at work FullAjax. <br/> the Standard loader of system: loading');
define('_FULLAJAX_MAIN_LOADERSTATICT', 'The loader static?');
define('_FULLAJAX_MAIN_LOADERSTATICD', 'If the loader does not move behind page of the user and is in the established place it is necessary to note YES. <br/> Under the standard the loader is not static!');
define('_FULLAJAX_MAIN_REPLACET', 'Replacement in references');
define('_FULLAJAX_MAIN_REPLACED', 'http://site.ru/#{here replacement}/board. Replacement should be necessarily unique!');
define('_FULLAJAX_MAIN_BLOCKLINKST', 'To block Ajax in references');
define('_FULLAJAX_MAIN_BLOCKLINKSD', 'Specify through a reference comma which FullAjax will ignore. <br/> for example: feedback,content,board,board/forum-');
define('_FULLAJAX_MAIN_STORAGET', 'System Storage');
define('_FULLAJAX_MAIN_STORAGED', 'Read here: <a href="http://habrahabr.ru/blogs/AJAX/26784/">http://habrahabr.ru/blogs/AJAX/26784/</a>');
define('_FULLAJAX_MAIN_FREECODET', 'The code');
define('_FULLAJAX_MAIN_FREECODED', 'Add the code to system');
define('_LOG', 'Adjustment of logs');
define('_LOG_MAIN', 'Logs errors'); 
define('_LOG_MAIN_PHPERRORT', 'Errors php');
define('_LOG_MAIN_PHPERRORD', 'If at script performance there were errors they will be brought in broad logs');
define('_LOG_MAIN_QUERYERRORT', 'Filtration errors');
define('_LOG_MAIN_QUERYERRORD', 'At attempt of breaking or at detection of danger the system will write down the information in a broad log and will stop malefactors');
define('_LOG_MAIN_DBERRORT', 'Database errors');
define('_LOG_MAIN_DBERRORD', 'logs Database errors');
define('_LOG_MAIN_ACCESERRORT', 'Access and site errors');
define('_LOG_MAIN_ACCESERRORD', 'In a broad log errors 403,404, and also unsuccessful inputs in the control panel will be written down');
define('_LOG_MAIN_COMPRESSSIZET', 'The limiting size of a file');
define('_LOG_MAIN_COMPRESSSIZED', 'It is underlined in bytes. After achievement of this size, the broad log will be packed in gz archive and hidden on the server.');

define('_CACHE_CONFIG', 'Options cache');
define('_CACHE_TPL', 'Structure of files TPL');
define('_CACHE_TPL_DESC', 'Cache structure and presence tpl files');
define('_CACHE_BLOCK', 'Blocks and modules');
define('_CACHE_BLOCK_DESC', 'Allows not to make inquiry at each updating of page');
define('_CACHE_CAT', 'Categories');
define('_CACHE_CAT_DESC', 'Cache the complete list of categories, reduces requirement for separate inquiry');
define('_CACHE_USER', 'Data of the user');
define('_CACHE_USER_DESC', 'Stores the actual information on the user');

define('_CONFIG_MODULES', 'Adjustment of modules:');

define('_BACKUP_NAME', 'Backup copies');
define('_BACKUP_ADD', 'Backup copy creation');
define('_BACKUP_ERROR_0', 'You have not chosen modules for reserve copying! Return <a href="javascript:history.go(-1)" title="Back">back</a> also make a choice.');
define('_BACKUP_ERROR_1', 'You have added an incorrect file of configurations');
define('_BACKUP_MAKE_COPY', 'Create copy');
define('_BACKUP_RESTORE_FILE', 'Restoration from a file:');
define('_BACKUP_RESTORE_DESC', 'To restore from a backup copy');
define('_BACKUP_RESTORE_NAME', 'Backup copy restoration');
define('_BACKUP_RESTORE_LOG_1', 'Preservation of configurations in');
define('_BACKUP_RESTORE_LOG_2', 'Successfully');

define('_SOCIAL_NAME', 'Setting authorization through social networks');
define('_SOCIAL_SW', 'Main');
define('_SOCIAL_SWITCH', 'Authorization through social networks');
define('_SOCIAL_SWITCH_DESC', 'Allow Authorization through social networks?');
define('_SOCIAL_PASS', 'Password at the entrance');
define('_SOCIAL_PASS_DESC', 'Prompt for password when logging? (Recommended option, improves safety!)');
define('_SOCIAL_ADMIN', 'Authorization administrator');
define('_SOCIAL_ADMIN_DESC', 'Allow authorization through social networking site administrator?');
define('_SOCIAL_IS', 'Allow authorization');
define('_SOCIAL_IS_DESC', 'Allow authorization through this social network?');
define('_SOCIAL_ID', 'Site ID');
define('_SOCIAL_ID_DESC', 'Site ID that you can get at the following address');
define('_SOCIAL_SECRET', 'The secret key');
define('_SOCIAL_SECRET_DESC', 'The private key that you can get at the following address');
define('_SOCIAL_PUBLIC', 'Public key');
define('_SOCIAL_PUBLIC_DESC', 'The public key that you can get at the following address');

define('_SOCIAL_CONFIG_VK', 'Settings on VKontakte');
define('_SOCIAL_CONFIG_VK_URL', 'https://vk.com/editapp?act=create');
define('_SOCIAL_CONFIG_OK', 'Settings on Odnoklassniki');
define('_SOCIAL_CONFIG_OK_URL', 'http://ok.ru/devaccess');
define('_SOCIAL_CONFIG_FB', 'Settings on Facebook');
define('_SOCIAL_CONFIG_FB_URL', 'https://developers.facebook.com/apps');
define('_SOCIAL_CONFIG_GG', 'Settings on Google+');
define('_SOCIAL_CONFIG_GG_URL', 'https://code.google.com/apis/console/');
define('_SOCIAL_CONFIG_YA', 'Settings on Yandex');
define('_SOCIAL_CONFIG_YA_URL', 'https://oauth.yandex.ru/client/new');
define('_SOCIAL_CONFIG_MM', 'Settings on Mail.ru');
define('_SOCIAL_CONFIG_MM_URL', 'http://api.mail.ru/sites/my/add');