<?php

/**
* @name        JMY CMS
* @link        http://jmy.su/
* @copyright   Copyright (C) 2012-2016 JMY LTD
* @license     LICENSE.txt (see attached file)
* @version     VERSION.txt (see attached file)
* @author      Komarov Ivan
*/

define('_BASE_GUEST_NAME', 'Guest (name)');
define('_BASE_GUEST_MAIL', 'Guest (E-mail)');
define('_BASE_USER_NAME', 'User');
define('_BASE_NAME', 'Name');
define('_BASE_LIST', 'List');
define('_BASE_CLEAR', 'Clear');
define('_BASE_DELETE', 'Delete');
define('_BASE_RESTORE', 'Restore');
define('_BASE_EMAIL', 'E-mail');
define('_BASE_SITE', 'Site');
define('_BASE_CONFIG', 'Options');
define('_BASE_GENDER', 'Gender');
define('_BASE_DATE', 'Date');
define('_BASE_ACTIONS', 'Action');
define('_BASE_FILE', 'File');
define('_BASE_GENDER_MALE', 'Male');
define('_BASE_GENDER_FEMALE', 'Female');
define('_BASE_INFO_0', 'Action is successfully executed. <a href="javascript:history.go(-1)" >return.</a>');
define('_BASE_ERROR_0', 'Obligatory fields have not been filled return <a href="javascript:history.go(-1)" title="back">back</a> also rectify errors!');
define('_BASE_ACTIVATE', 'Activate');
define('_BASE_DACTIVATE', 'Activate');
define('_BASE_EDIT', 'Edit');
define('_BASE_DELITE', 'Delete');

define('_PANEL_MENU_MAIN', 'Main');
define('_PANEL_MENU_NEWS', 'Materials');
define('_PANEL_MENU_NEWS_MANAGER', 'Manager of materials');
define('_PANEL_MENU_NEWS_CAT', 'Manager of categories');
define('_PANEL_MENU_NEWS_XFIELDS', 'Additional fields');
define('_PANEL_MENU_NEWS_FM', 'File manager');
define('_PANEL_MENU_USER', 'Users');
define('_PANEL_MENU_USER_MANAGER', 'Manager of users');
define('_PANEL_MENU_USER_GROUP', 'Groups');
define('_PANEL_MENU_USER_COMMENT', 'Comments');
define('_PANEL_MENU_USER_POLL', 'Polls');
define('_PANEL_MENU_COM', 'Components');
define('_PANEL_MENU_COM_BLOG', 'Blog manager');
define('_PANEL_MENU_COM_FORUM', 'Forum');
define('_PANEL_MENU_COM_GALLERY', 'Gallery');
define('_PANEL_MENU_COM_GUESTBOOK', 'Guest book');
define('_PANEL_MENU_COM_STATIC', 'Static pages');
define('_PANEL_MENU_CONFIG', 'Options');
define('_PANEL_MENU_EXP', 'Expansions');
define('_PANEL_MENU_EXP_MODULES', 'Modules');
define('_PANEL_MENU_EXP_BLOCKS', 'HTML (PHP) blocks');
define('_PANEL_MENU_EXP_LANG', 'Editor languages');
define('_PANEL_MENU_EXP_TPL', 'Templates');
define('_PANEL_MENU_OTHER', 'Other');
define('_PANEL_MENU_OTHER_MAP', 'Sitemap');
define('_PANEL_MENU_OTHER_SMILES', 'Smiles');
define('_PANEL_MENU_OTHER_BD', 'Database');
define('_PANEL_MENU_OTHER_LOG', 'Logs errors');
define('_PANEL_MENU_OTHER_UPDATE', 'Update');
define('_PANEL_SUNMENU_WELCOME', 'Welcome');
define('_PANEL_SUNMENU_IP', 'Yours IP:');
define('_PANEL_SUNMENU_PROFILE', 'Profile options');
define('_PANEL_SUNMENU_STATS', 'Statistics');
define('_PANEL_SUNMENU_VIEW', 'Site viewing');
define('_PANEL_SUNMENU_HELP', 'Help');
define('_PANEL_SUNMENU_EXIT', 'Exit');
define('_PANEL_SUNMENU_NOTIF', 'Notices');
define('_PANEL_SEARCH', 'Search');

define('_THERE_IS', 'Is');
define('_DATE_PUB', 'Publication date');
define('_ACTIVATE_RATING', 'Activate rating');
define('_ACTIVATE_COMMENTS', 'Activate comments');
define('_TOP_SET', 'Fix in a top');
define('_PUBLIC_INDEX', 'Place on the main');
define('_TAB_MAIN', 'Core');
define('_TAB_CONTENT', 'Content');
define('_TAB_CONTROL', 'Management');
define('_U_ADDNEWS', 'Add news');
define('_U_ADDBLOCK', 'Add <br />block');
define('_U_CONF', 'Basic options');
define('_U_ADDPAGE', 'Add page');
define('_U_ADDCAT', 'Add category');
define('_U_ADDVOT', 'Add poll');
define('_U_TPL', 'Site templates');
define('_U_USR', 'Users of system');
define('_U_RSS', 'RSS Grabber');
define('_APANEL', 'Control panel');
define('_YOURIP', 'Yours IP:');
define('_SYSVER', 'System version');
define('_DBSIZE', 'Size of a database');
define('_ALLUSERS', 'Total users');
define('_ALLNEWS', 'Total news');
define('_TIC', 'ТИЦ a site');
define('_PR', 'PR a site');
define('_PUBLICATIONS', 'Receipts');

define('_INSTALLEX', 'Remove a file install.php - it threatens safety of your site!');
define('_ONMODER', 'Attention! Users have added fresh materials!');
define('_UPDATE_JMY', 'Attention! There was new version JMY CMS. Be on a wave!');
define('_NO_VERSION', 'Attention! The file with version JMY CMS is not found! Restore it!');
define('_NOT_NOTIF', 'There are no notices');
define('_LASTLOG', 'Last inputs');
define('_FALSELOG', 'Unsuccessful inputs');
define('_LOGSCLEANED', 'Logs are cleared');
define('_TABLECLEANED', 'Table is cleared');
define('_NONINF', 'Information is absent');
define('_CACHE_CLEANED', 'Cache is removed');
define('_CHECKUPDATE', 'Check up updatings');
define('_NO_UPDATE', 'At present updatings are not present.');
define('_NO_NEWS', 'At present news are not present.');
define('_NO_TURNS', 'At you does not remain attempts, try later.');
define('_FALSE_TURN', 'The password is entered not truly! You still had {turns} attempt');
define('_SYSTEM_STATISTIC', 'Statistics of system');
define('_AP_WELOCME', 'Welcome to the control panel');
define('_LOG_WRITE', 'Input {nick} in the control panel.');
define('_EMPTY_LOGIN', 'The name or the password are empty!');
define('_SAVE', 'Save');
define('_SITE', 'Site');
define('_GOOD_LOGIN', 'Input [nick] in the control panel.');
define('_BAD_LOGIN', 'Unsuccessful input [nick] in the control panel. The entered password [pass]');
define('_BLOCKS_NOT_FOUND', 'Blocks it is not found');
define('_DELETE_COMMENT', 'Delete comment?');

define('_UPLOAD', 'Load');
define('_CHOOSE', 'Choose');
define('_CHOOSED', 'Chosen');

define('_MAIN_MAIN', 'Control panel');
define('_MAIN_CREATE', 'Create');
define('_MAIN_CREATE_DESC', 'Add material');
define('_MAIN_LIST', 'List');
define('_MAIN_LIST_DESC', 'Edit news');
define('_MAIN_STATIC', 'Page');
define('_MAIN_STATIC_DESC', 'List pages');
define('_MAIN_CONF', 'Options');
define('_MAIN_CONF_DESC', 'System options');
define('_MAIN_USER', 'Users');
define('_MAIN_COMM', 'Comments');
define('_MAIN_LAST_USER', 'Last comments');
define('_MAIN_LAST_COMM', 'Last users');
define('_MAIN_EMPTY_INFO', 'Information is absent');
define('_MAIN_EMPTY_COMM', 'Comments are absent');

define('_MAIN_CACHE', 'Cache');
define('_MAIN_CACHE_SIZE', 'Size cache');
define('_MAIN_CACHE_INFO', 'At you on a site the system cache databases is activated. And it means that inquiries passing through mysql a system class, register in a cache and are updated after a certain time interval. If you made changes out of a site, in structure of a database or have disconnected it at all, I advise to clean a cache of system the button more low.');
define('_MAIN_CLEARCACHE', 'Clear cache');

define('_BBLOCK', 'Block');
define('_BLOCK_ADD', 'Block add');
define('_BLOCK_TYPE_DEL', 'Are you sure you want to delete ');
define('_BLOCK_ADDING', 'Block addition');
define('_BLOCK_TITLE_TT', 'Block heading displayed on a site');
define('_BLOCK_FILE', 'File');
define('_BLOCK_FILE_WITHOUT', 'No file');
define('_BLOCK_DESTANATION', 'Block arrangement');
define('_BLOCK_CONTENT', 'Maintenance');
define('_BLOCK_POS', 'Position');
define('_BLOCK_POS_TT', 'Leave empty and the block will get to the end');
define('_BLOCK_GROUPS', 'Well groups');
define('_BLOCK_GROUPS_TT', 'For a choice of several groups clamp CTRL.');
define('_BLOCK_ACTIVE', 'Active');
define('_BLOCK_ALL', 'In all');
define('_BLOCK_FREE', 'Free');
define('_BLOCK_INDEX', 'Only on the main');
define('_BLOCK_UNSHOW', 'Negation of the noted');
define('_BLOCK_FILECHOOSED', '<b>The file is chosen, content editing is impossible!</b> (<u>Choose There is no File and editing will be accessible</u>)');
define('_BLOCK_FOR_TPL', 'For a template');
define('_BLOCK_DELETEFROM_TYPE', 'To remove blocks of this type');
define('_BLOCK_TYPE_TITLE', 'Type heading');
define('_BLOCK_TYPEF_TT', 'Type for processing in templates');
define('_BLOCK_TYPE_TITLE_TT', 'Type heading displayed in the Control panel');
define('_BLOCK_ADD_TYPE', 'Add block type');
define('_BLOCK_STANDART', 'Adjustment of standard blocks');

define('_LOG_LOG', 'System logs');
define('_LOG_OK_COM', 'Action is successfully executed');
define('_LOG_OK_CLEAR', 'Logs of errors are successfully cleared! <a href="javascript:history.go(-1)" title="back">Return back</a>');
define('_LOG_NAME', 'Safety logs');
define('_LOG_ERROR', 'errors');
define('_LOG_CLEAR', 'Clear logs');
define('_LOG_EMPTY', 'Logs are empty!');

define('_SMAILE_SMAILE', 'Smile');
define('_SMAILE_SMAILES', 'Smiles');
define('_SMAILE_LIST', 'List smiles');
define('_SMAILE_ADD', 'Add smile');
define('_SMAILE_TAG', 'BB tag');
define('_SMAILE_DESC', 'Description');
define('_SMAILE_URL', 'URL smiles');
define('_SMAILE_DEL', 'Delete');
define('_SMAILE_FOLDER', 'From a folder');
define('_SMAILE_TITLE', 'Management of smiles');
define('_SMAILE_INFO_1', 'Configurations are successfully kept');
define('_SMAILE_INFO_2', 'The smile is successfully added');
define('_SMAILE_INFO_3', 'The smile is not added, as is not found on the server.');
define('_SMAILE_FOUND', 'It is found');
define('_SMAILE_NOT_FOUND', 'It is not found');

define('_USER_USER', 'User');
define('_USER_USERS', 'Users');
define('_USER_TITLE', 'Management of users');
define('_USER_NAVIGATION', 'Navigation');
define('_USER_ADD', 'Addition of the user');
define('_USER_FULL_SEARCH', 'Expanded search');
define('_USER_INPUT', 'Enter name');
define('_USER_SEARCH', 'Search');
define('_USER_SHORT', 'Sort on:');
define('_USER_ABC', 'The alphabet');
define('_USER_LAST_V', 'Last visit');
define('_USER_ID', 'ID');
define('_USER_SEARCH_BY', 'Search on:');
define('_USER_NICK', 'Nick');
define('_USER_EMAIL', 'E-Mail');
define('_USER_NAME', 'Name');
define('_USER_PASS', 'Password');
define('_USER_GROUP', 'Group');
define('_USER_SONAME', 'Surname');
define('_USER_IP', 'IP adress');
define('_USER_G_D', 'Any');
define('_USER_BANNED', 'Banned');
define('_USER_ADD_INFO_1', 'Such user already exists in system');
define('_USER_ADD_INFO_2', 'The user is successfully added!');

define('_POLL_POLLS', 'Polls');
define('_POLL_POLL', 'Poll');
define('_POLL_LIST', 'List polls');
define('_POLL_VOTE', 'Poll theme:');
define('_POLL_VAR', 'Variants');
define('_POLL_ANS', 'Answers');
define('_POLL_MAX', 'As much as possible');
define('_POLL_DEL', 'Delete poll');
define('_POLL_EMPTY', 'Polls are not present!');
define('_POLL_ADD', 'Add poll');
define('_POLL_EDIT', 'Edit poll');
define('_POLL_NAME', 'Poll name');
define('_POLL_VARS', 'Variants of answers');
define('_POLL_VARS_DESC', 'On every line new variant of the answer');
define('_POLL_VARS_DESC_E', 'The name of a variant Quantity of voices');
define('_POLL_MAXS', 'As much as possible answers');
define('_POLL_MAXS_DESC', 'If not 0 that users can choose some variants.');
define('_POLL_INFO_0', 'Poll is added. <a href="{ADMIN}/voting">To polls</a>');
define('_POLL_INFO_1', 'Poll is updated. <a href="{ADMIN}/voting">To polls</a>');

define('_DB_DB', 'Database');
define('_DB_TABLE', 'Table');
define('_DB_TABLE_NAME', 'Table name');
define('_DB_TABLE_CODE', 'Coding');
define('_DB_TABLE_NUMB', 'Lines');
define('_DB_TABLE_SIZE', 'Size');
define('_DB_TABLE_DEL', 'Table removal');
define('_DB_TABLE_DELETE', 'It is successfully removed.');
define('_DB_TRUNCATE', 'Clear table');
define('_DB_CLEAR', 'Table clarification');
define('_DB_CLEAR_OK', 'It is successfully cleared.');
define('_DB_DELETE', 'Delete table');
define('_DB_CHOICE', 'Choose tables');
define('_DB_ABOUT', 'Description');
define('_DB_OP_NAME', 'Optimisation');
define('_DB_OP_DO', 'To optimise');
define('_DB_OP_TEXT', 'You can make database optimisation, thereby will be saved a few places on a disk, and also database work is accelerated. It is recommended to use the given function a minimum once a week.');
define('_DB_RE_NAME', 'Database repair');
define('_DB_RE_DO', 'Repair');
define('_DB_RE_TEXT', 'At unexpected stop MySQL of the server, during performance of any actions, there can be a damage of structure of tables, use of this function will help to solve to you this problem.');
define('_DB_BE_NAME', 'Reserve copying');
define('_DB_BE_DO', 'Backup');
define('_DB_BE_TEXT', 'For preservation in integrity of the data of a site it is necessary to do from time to time database backup copies, at loss of the data you can always return from backup a site.');
define('_DB_BE_COPY', 'Copies on the server');
define('_DB_BE_NO', 'Backups databases it is not revealed!');
define('_DB_BE_RES', 'Restore backup');
define('_DB_BE_DEL', 'Delete backup');
define('_DB_BE_ERROR', 'To execute backup it is impossible!');
define('_DB_BE_COM', 'The database backup copy is made and accessible in a folder: ');
define('_DB_BE_BACK', 'Return>>');
define('_DB_BE_SERVER', 'The information from the server:');
define('_DB_BE_DOWNLOAD', 'Download backup.');
define('_DB_BE_REST', 'DB restoration');
define('_DB_BE_REST_OK', 'The database is successfully restored.');
define('_DB_BE_REST_NO', 'It was not possible to restore a database!');
define('_DB_BB_NAME', 'Recalculation BB');
define('_DB_BB_DO', 'Update BB');
define('_DB_BB_START', 'Start');
define('_DB_BB_END', 'End');

define('_COM_COM', 'Comments');
define('_COM_OK', 'Action is successfully executed');
define('_COM_LIST', 'List comments');
define('_COM_LIST_M', 'The list of comments on a moderation');
define('_COM_NO', 'Comments are absent.');
define('_COM_ID', 'ID Comment');
define('_COM_EDIT', 'Comment editing');
define('_COM_ACT', 'Activate comment?');
define('_COM_TEXT', 'Comment text');
define('_COM_UPDATE', 'The comment is successfully updated.');
define('_COM_DELETE', 'Delete comment ');

define('_DOP_DOPS', 'Additional fields');
define('_DOP_TEMP', 'Code for an insert in a template');
define('_DOP_DEL', 'You are assured that want to remove ');
define('_DOP_EMPTY', 'Additional fields are absent.');
define('_DOP_EDIT_DOP', 'Edit field');
define('_DOP_EDIT', 'Edit');
define('_DOP_ADD_DOP', 'Add field');
define('_DOP_ADD', 'Add');
define('_DOP_ADD_DEF', 'Value by default:');
define('_DOP_ADD_TITLE', 'Field name:');
define('_DOP_ADD_DESC', 'Field description:');
define('_DOP_ADD_MODULE', 'Module:');
define('_DOP_ADD_TYPE', 'Field type:');
define('_DOP_ADD_USER', 'User part:');
define('_DOP_TYPE_0', 'Choose type');
define('_DOP_TYPE_1', 'One-line text');
define('_DOP_TYPE_2', 'Multilower case text');
define('_DOP_TYPE_3', 'Dropping out list');
define('_DOP_ERROR_1', 'You have not filled field heading!');
define('_DOP_ERROR_2', 'You have not filled the field description!');
define('_DOP_ERROR_3', 'You have not chosen field type!');
define('_DOP_ADDS', 'Field addition');
define('_DOP_EDITS', 'Field editing');
define('_DOP_INFO_1', 'The additional field is successfully updated!');
define('_DOP_INFO_2', 'The additional field is successfully added!');

define('_CONFIGURATION', 'System configurations');
define('_CONF_INF_TH', 'The information to reflexion');
define('_CONF_EXPAND', 'Open');
define('_CONF_SUMM', 'Total options');
define('_SUCCESS_SAVE', 'Parametres are successfully kept.');
define('_ACCEPT', 'Accept');

define('_CAT_PATH', 'Site categories');
define('_CAT_ADD', 'Category addition');
define('_CAT_ADDS', 'Categories are added');
define('_CAT_FAST_ADD', 'Fast addition');
define('_CAT_ADDSUCCESS', 'The category is successfully added. <a href="{ADMIN}/cats/add">Will return to addition</a> or <a href="{ADMIN}/cats">to see the list of categories</a>?');
define('_CAT_ADDFATAL', 'The category did not manage to be added, as not all fields have been filled return <a href="javascript:history.go(-1)" title="back">back</a> also try again!');
define('_CAT_UPDATESUCCESS', 'The category is successfully updated. <a href="{ADMIN}/cats">To see the list of categories</a>?');
define('_CAT_NAME', 'Category name');
define('_CAT_NAME_TT', 'Category heading displayed on a site');
define('_CAT_URL', 'Adress (URL)');
define('_CAT_URL_TT', 'The name for the address is possible in Russian, but without blanks!!');
define('_CAT_DESCR', 'Category description');
define('_CAT_DESCR_TT', 'Category description');
define('_CAT_KEYS', 'Keywords');
define('_CAT_KEYS_TT', 'Keywords for meta tags');
define('_CAT_ICON', 'Category icon');
define('_CAT_ICON_NO', 'No icon');
define('_CAT_ICON_TT', 'Category icon in the module.');
define('_CAT_INCAT', 'In a category');
define('_CAT_INCAT_TT', 'If want that your category was a subcategory.');
define('_CAT_INCAT_NO', 'No category');
define('_CAT_MODULE', 'Category module');
define('_CAT_UPDATE', 'Category updating');
define('_CAT_DELETE', 'Remove category - [cat]? \n\r All news too will be removed!');
define('_CAT_NO_CATS', 'Categories are not present, add the first!');
define('_CAT_LIST', 'List categories');
define('_CAT_LIST_TT', 'Enter categories the list. Each category on a new line');
define('_CAT_LIST_SUCCESS', 'The category "[name]" is added.  <br />');
define('_CAT_ERROR_1', 'You have not filled category heading!');

define('_TPL_TPL', 'Template');
define('_TPL_TPLS', 'Templates');
define('_TPL_UPLOAD_TPL', 'Load template:');
define('_TPL_UPLOAD_INF', 'Choose a file (in a format zip) a template which you want to build in system:');
define('_TPL_IN', 'Standard template for');
define('_TPL_OUT', 'Foreign template for');
define('_TPL_LOAD', 'Download template');
define('_TPL_DEL', 'Delete template');
define('_TPL_EDET', 'Edit template');
define('_TPL_EDET_CSS', 'Edit styles');
define('_TPL_NO_CSS', 'Choose css a file for editing!');
define('_TPL_EDET_CH', 'File choice tpl');
define('_TPL_EDET_CSS_CH', 'File choice css');
define('_TPL_FOLD_MAIN', 'Main');
define('_TPL_FOLD_BLOG', 'Blogs');
define('_TPL_FOLD_BOARD', 'Forum');
define('_TPL_FOLD_COMM', 'Comments');
define('_TPL_FOLD_CONTENT', 'Pages');
define('_TPL_FOLD_GALLERY', 'Gallery');
define('_TPL_FOLD_GUEST', 'Guest book');
define('_TPL_FOLD_NEWS', 'News');
define('_TPL_FOLD_PM', 'PM');
define('_TPL_FOLD_PROFILE', 'Profile');
define('_TPL_FOLD_SEARCH', 'Search'); 
define('_TPL_NAME_INDEX', 'Main page');
define('_TPL_NAME_INFO', 'Information');
define('_TPL_NAME_PAGE', 'Navigation');
define('_TPL_NAME_SITEMAP', 'Sitemap');
define('_TPL_NAME_TABLE', 'Content table');
define('_TPL_NAME_TITLE', 'Headings');
define('_TPL_NAME_WARNING', 'Alerts');
define('_TPL_NAME_POLL', 'Polls');
define('_TPL_NAME_FEEDBACK', 'Feedback');
define('_TPL_NAME_BLOCK', 'Conclusion PHP of blocks');
define('_TPL_NAME_MAINPAGE', 'Content on the main');
define('_TPL_NAME_CUSTOMS', 'Conclusion of news on a template');
define('_TPL_NAME_BB', 'BB Code');
define('_TPL_NAME_COM', 'Comment');
define('_TPL_NAME_N_CAT', 'News in a category');
define('_TPL_NAME_N_VIEW', 'News viewing');
define('_TPL_NAME_N_MAIN', 'News on the main');
define('_TPL_NAME_N_ADD', 'Add news');
define('_TPL_NAME_CSS_ENG', 'Style of system');
define('_TPL_NAME_CSS_THM', 'Style of a template');
define('_TPL_INFO_0', 'The template is successfully removed.');
define('_TPL_INFO_1', 'It is impossible to remove a template. Probably it is chosen, as the basic.');
define('_TPL_INFO_2', 'The template is successfully chosen!');
define('_TPL_INFO_3', 'The template is successfully loaded on a site!');
define('_TPL_INFO_4', 'It was not possible to load a template, check up correctness of archive.');
define('_TPL_INFO_5', 'The template is successfully kept.');
define('_TPL_INFO_6', 'Style is successfully kept.');

define('_GROUP_GROUPS', 'Groups');
define('_GROUP_NAME_SPECIAL', 'Special');
define('_GROUP_NAME_PROTECTED', 'Protected');
define('_GROUP_DEL', 'Remove group - ');
define('_GROUP_UPDATE', 'Group updating');
define('_GROUP_ADD', 'Group addition');
define('_GROUP_EMPTY', 'Groups are not present!');
define('_GROUP_NAME', 'Group name');
define('_GROUP_SPECIAL', 'Special group');
define('_GROUP_SPECIAL_DESC', 'At a choice of the given point, all options are void, the group bears only informative sense');
define('_GROUP_POINTS', 'Quantity of points');
define('_GROUP_POINTS_DESC', 'If group special and you want, that it was appointed depending on quantity of points of the user, fill the given field');
define('_GROUP_RIGHT_GUEST', 'Right guest');
define('_GROUP_RIGHT_USER', 'Right user');
define('_GROUP_RIGHT_MODER', 'Right moderator');
define('_GROUP_RIGHT_ADMIN', 'Right administrator');
define('_GROUP_RIGHT_BAN', 'Banned?');
define('_GROUP_RIGHT_FULL', 'Just causes?');
define('_GROUP_RIGHT_HIDE', 'Show under a tag [hide]?');
define('_GROUP_ATTACH_VIEW', 'Show attachment?');
define('_GROUP_ATTACH_LOAD', 'To allow to load attachment');
define('_GROUP_RIGHT_ADDNEWS', 'To resolve addition of materials');
define('_GROUP_RIGHT_COMMENT', 'To resolve addition of comments');
define('_GROUP_VIEW_RAITING', 'To show a rating');
define('_GROUP_AVATAR_WIGHT', 'The maximum width of an avatar');
define('_GROUP_PM', 'Maximum quantity PM:');
define('_GROUP_ICON', 'Group icon');
define('_GROUP_COLOR', 'Colour of groups');
define('_GROUP_INFO_0', 'The group is successfully added!');
define('_GROUP_INFO_1', 'The group is successfully updated!');
define('_GROUP_CONFIG_NAME', 'Points of the user');
define('_GROUP_CONFIG_ADDNEWS', 'News addition');
define('_GROUP_CONFIG_ADDNEWS_DESC', 'How many points to give for news addition');
define('_GROUP_CONFIG_ADDCOMM', 'Comment addition');
define('_GROUP_CONFIG_ADDCOMM_DESC', 'How many points to give for comment addition');
define('_GROUP_CONFIG_REG', 'Registration');
define('_GROUP_CONFIG_REG_DESC', 'The point is charged at registration');
define('_GROUP_CONFIG_CARMA', 'Karma exhibiting');
define('_GROUP_CONFIG_CARMA_DESC', 'If to the user have raised a karma, the given quantity of points increases');
define('_GROUP_CONFIG_FRIENDS', 'Addition in friends');
define('_GROUP_CONFIG_FRIENDS_DESC', 'If the user has a friend, add points');
define('_GROUP_CONFIG_VOTE', 'Estimation of publications');
define('_GROUP_CONFIG_VOTE_DESC', 'If the user has estimated the publication we add points');

define('_CONFIG_KEYWORDS', 'Keywords the module');
define('_CONFIG_SEO_DESC', 'For SEO site optimisation');
define('_CONFIG_DESC', 'Description the module');

define('_SEARCH_ERROR_0', 'To search you must enter a keyword!');
define('_SEARCH_ERROR_1', 'Search on this request returned no results!');
define('_SEARCH_REF', 'go');

define('_UPDATE_MAIN', 'Updates');
define('_UPDATE_NO', 'Currently there are no updates!');
define('_UPDATE_OK', 'The new version has been successfully installed! <br> Enjoy using!');
define('_UPDATE_ERROR_0', 'The upgrade process unknown error occurred!');
define('_UPDATE_BACKUP_OK', 'Backup data successfully created! (tmp/backup)');
define('_UPDATE_BACKUP_NO', 'Failed to create a backup system to further upgrade is not recommended!');
define('_UPDATE_START', 'UPDATE JMY CMS');
define('_UPDATE_NEW', 'THE NEW VERSION JMY CMS!');
define('_UPDATE_DESC', 'Ready to upgrade to upgrade to the new version, click on the button below!');
define('_UPDATE_B_NEXT', 'Continue update');
define('_UPDATE_B_AGAIN', 'Start from the beginning');

