<?php

/**
* @name        JMY CMS
* @link        http://jmy.su/
* @copyright   Copyright (C) 2012-2016 JMY LTD
* @license     LICENSE.txt (see attached file)
* @version     VERSION.txt (see attached file)
* @author      Komarov Ivan
*/

define('_BASE_GUEST_NAME', 'Гость (Имя)');
define('_BASE_GUEST_MAIL', 'Гость (E-mail)');
define('_BASE_USER_NAME', 'Пользователь');
define('_BASE_NAME', 'Имя');
define('_BASE_LIST', 'Список');
define('_BASE_CLEAR', 'Очистить');
define('_BASE_INFO', 'Информация');
define('_BASE_ERROR', 'Ошибка');
define('_BASE_BACK', 'Вернуться');
define('_BASE_DELETE', 'Удалить');
define('_BASE_RESTORE', 'Восстановить');
define('_BASE_EMAIL', 'E-mail');
define('_BASE_SITE', 'Сайт');
define('_BASE_CONFIG', 'Настройки');
define('_BASE_GENDER', 'Пол');
define('_BASE_DATE', 'Дата');
define('_BASE_HELP', 'Помощь');
define('_BASE_CLOSE', 'Закрыть');
define('_BASE_ACTIONS', 'Действие');
define('_BASE_FILE', 'Файл');
define('_BASE_GENDER_MALE', 'Мужской');
define('_BASE_GENDER_FEMALE', 'Женский');
define('_BASE_INFO_0', 'Действие успешно выполнено. <a href="javascript:history.go(-1)" >Вернуться.</a>');
define('_BASE_ERROR_0', 'Обязательные поля не были заполнены вернитесь и исправьте ошибки!');
define('_BASE_ACTIVATE', 'Активировать');
define('_BASE_DACTIVATE', 'Активировать');
define('_BASE_EDIT', 'Редактировать');
define('_BASE_DELITE', 'Удалить');
define('_BASE_CONFIRM', 'Подтвердите ваше действие!');
define('_BASE_VERSION', 'Версия');
define('_BASE_INSTALL', 'Установить');

define('_PANEL_MENU_MAIN', 'Главная');
define('_PANEL_MENU_NEWS', 'Материалы');
define('_PANEL_MENU_NEWS_MANAGER', 'Менеджер материалов');
define('_PANEL_MENU_NEWS_CAT', 'Менеджер категорий');
define('_PANEL_MENU_NEWS_XFIELDS', 'Дополнительные поля');
define('_PANEL_MENU_NEWS_FM', 'Менеджер файлов');
define('_PANEL_MENU_USER', 'Пользователи');
define('_PANEL_MENU_USER_MANAGER', 'Менеджер пользователей');
define('_PANEL_MENU_USER_GROUP', 'Группы');
define('_PANEL_MENU_USER_COMMENT', 'Комментарии');
define('_PANEL_MENU_USER_POLL', 'Опросы');
define('_PANEL_MENU_COM', 'Компоненты');
define('_PANEL_MENU_COM_BLOG', 'Менеджер блогов');
define('_PANEL_MENU_COM_FORUM', 'Форум');
define('_PANEL_MENU_COM_GALLERY', 'Галерея');
define('_PANEL_MENU_COM_GUESTBOOK', 'Гостевая книга');
define('_PANEL_MENU_COM_STATIC', 'Статические страницы');
define('_PANEL_MENU_CONFIG', 'Настройки');
define('_PANEL_MENU_EXP', 'Расширения');
define('_PANEL_MENU_EXP_MODULES', 'Модули');
define('_PANEL_MENU_EXP_BLOCKS', 'HTML (PHP) блоки');
define('_PANEL_MENU_EXP_LANG', 'Редактор языков');
define('_PANEL_MENU_EXP_TPL', 'Шаблоны');
define('_PANEL_MENU_OTHER', 'Прочие');
define('_PANEL_MENU_OTHER_MAP', 'Карта сайта');
define('_PANEL_MENU_OTHER_SMILES', 'Смайлы');
define('_PANEL_MENU_OTHER_BD', 'База данных');
define('_PANEL_MENU_OTHER_LOG', 'Логи ошибок');
define('_PANEL_MENU_OTHER_UPDATE', 'Обновления');
define('_PANEL_SUNMENU_WELCOME', 'Добро пожаловать');
define('_PANEL_SUNMENU_STATUS', 'Ваш статус:');
define('_PANEL_SUNMENU_ALWAYS', 'Всегда в сети');
define('_PANEL_SUNMENU_IP', 'Ваш IP:');
define('_PANEL_SUNMENU_PROFILE', 'Настройки профиля');
define('_PANEL_SUNMENU_STATS', 'Статистика');
define('_PANEL_SUNMENU_VIEW', 'Просмотр');
define('_PANEL_SUNMENU_HELP', 'Помощь');
define('_PANEL_SUNMENU_EXIT', 'Выход');
define('_PANEL_SUNMENU_NOTIF', 'Уведомления');
define('_PANEL_SEARCH', 'Поиск');

define('_PANEL_STATS_NUM_USER', 'Колличество пользоваетелей');
define('_PANEL_STATS_NUM_COMM', 'Колличество отзывов');
define('_PANEL_STATS_NUM_NEWS', 'Колличество материалов');
define('_PANEL_STATS_NUM_BLOG', 'Колличество блогов');
define('_PANEL_STATS_VISIT', 'Посещаемость');
define('_PANEL_STATS_VISITOR', 'Визитов');
define('_PANEL_STATS_VIEWS', 'Просмотров');
define('_PANEL_STATS_USERS', 'Пользователи');
define('_PANEL_STATS_FILTER', 'Фильтр');
define('_PANEL_STATS_SERVER_STATS', 'Серверная информация');
define('_PANEL_STATS_SERVER_SPACE', 'Занятое место');
define('_PANEL_STATS_SERVER_CPU', 'CPU');
define('_PANEL_STATS_SERVER_RAM', 'RAM память');
define('_PANEL_STATS_SEO', 'SEO информация');

define('_THERE_IS', 'Есть');
define('_DATE_PUB', 'Дата публикации');
define('_ACTIVATE_RATING', 'Активировать рейтинг');
define('_ACTIVATE_COMMENTS', 'Активировать комментарии');
define('_TOP_SET', 'Закрепить в топе');
define('_PUBLIC_INDEX', 'Разместить на главной');
define('_TAB_MAIN', 'Основное');
define('_TAB_CONTENT', 'Контент');
define('_TAB_CONTROL', 'Управление');
define('_U_ADDNEWS', 'Добавить новость');
define('_U_ADDBLOCK', 'Добавить <br />блок');
define('_U_CONF', 'Основные настройки');
define('_U_ADDPAGE', 'Добавить страницу');
define('_U_ADDCAT', 'Добавить категорию');
define('_U_ADDVOT', 'Добавить опрос');
define('_U_TPL', 'Шаблоны сайта');
define('_U_USR', 'Пользователи системы');
define('_U_RSS', 'RSS Граббер');
define('_APANEL', 'Панель управления');
define('_YOURIP', 'Ваш IP:');
define('_SYSVER', 'Версия системы');
define('_DBSIZE', 'Размер базы данных');
define('_ALLUSERS', 'Всего пользователей');
define('_ALLNEWS', 'Всего новостей');
define('_TIC', 'ТИЦ сайта');
define('_PR', 'PR сайта');
define('_PUBLICATIONS', 'Поступления');
define('_FORWARD', 'Вперёд');

define('_INSTALLEX', 'Удалите файл install.php - он угрожает безопасности вашего сайта!');
define('_ONMODER', 'Внимание! Пользователи добавили свежие материалы!');
define('_UPDATE_JMY', 'Внимание! Вышла новая версия JMY CMS. Будьте на волне!');
define('_NO_VERSION', 'Внимание! Не найден файл с версией JMY CMS! Восстановите его!');
define('_NOT_NOTIF', 'Нет уведомлений');
define('_LASTLOG', 'Последние входы');
define('_FALSELOG', 'Неудачные входы');
define('_LOGSCLEANED', 'Логи очищены');
define('_TABLECLEANED', 'Таблица очищена');
define('_NONINF', 'Информация отсутствует');
define('_CACHE_CLEANED', 'кэш удалён');
define('_CHECKUPDATE', 'Проверить обновления');
define('_NO_UPDATE', 'В данный момент обновлений нет.');
define('_NO_NEWS', 'В данный момент новостей нет.');
define('_NO_TURNS', 'У вас не осталось попыток, попробуйте позже.');
define('_FALSE_TURN', 'Пароль введён не верно! У вас осталось {turns} попытка(и)');
define('_SYSTEM_STATISTIC', 'Статистика системы');
define('_AP_WELOCME', 'Добро пожаловать в панель управления');
define('_LOG_WRITE', 'Вход {nick} в панель управления.');
define('_EMPTY_LOGIN', 'Имя или пароль пусты!');
define('_SAVE', 'Сохранить');
define('_SITE', 'Сайт');
define('_GOOD_LOGIN', 'Вход [nick] в панель управления.');
define('_BAD_LOGIN', 'Неудчаный вход [nick] в панель управления. Вводимый пароль [pass]');
define('_BLOCKS_NOT_FOUND', 'Блоков не найдено');
define('_DELETE_COMMENT', 'Удалить комментарий?');

define('_UPLOAD', 'Загрузить');
define('_CHOOSE', 'Выбрать');
define('_CHOOSED', 'Выбрано');

define('_MAIN_MAIN', 'Панель управления');
define('_MAIN_CREATE', 'Создать');
define('_MAIN_CREATE_DESC', 'Добавить материал');
define('_MAIN_LIST', 'Список');
define('_MAIN_LIST_DESC', 'Редактировать');
define('_MAIN_STATIC', 'Страница');
define('_MAIN_STATIC_DESC', 'Список страниц');
define('_MAIN_CONF', 'Настройки');
define('_MAIN_CONF_DESC', 'Настройки системы');
define('_MAIN_USER', 'Пользователи');
define('_MAIN_COMM', 'Комментарии');
define('_MAIN_LAST_USER', 'Последние пользователи:');
define('_MAIN_LAST_COMM', 'Последние комментарии:');
define('_MAIN_EMPTY_INFO', 'Информация отсутствует!');
define('_MAIN_EMPTY_COMM', 'Комментарии отсутствуют!');
define('_MAIN_EMPTY_SIGN', 'К сожалению, подпись у пользователя отсутствует!');



define('_MAIN_CACHE', 'Кэширование');
define('_MAIN_CACHE_SIZE', 'Размер кэша');
define('_MAIN_CACHE_INFO', 'У вас на сайте активирована система кэширования базы данных. А это значит, что запросы проходящие через mysql класс системы, записываются в кэш и обновляются после определённого промежутка времени. Если Вы вносили изменения вне сайта, в структуру базы данных или отключили её вовсе, советую почистить кэш системы кнопкой ниже.');
define('_MAIN_CLEARCACHE', 'Очистить кэш');

define('_BBLOCK', 'блок');
define('_BLOCK_ADD', 'Добавить блок');
define('_BLOCK_EDIT', 'Редактировать блок');
define('_BLOCK_ADDING', 'Добавление блока');
define('_BLOCK_TITLE_TT', 'Заголовок блока отображаемый на сайте');
define('_BLOCK_FILE', 'Файл');
define('_BLOCK_FILE_WITHOUT', 'Без файла');
define('_BLOCK_DESTANATION', 'Расположение блока');
define('_BLOCK_CONTENT', 'Содержание');
define('_BLOCK_POS', 'Позиция');
define('_BLOCK_POS_TT', 'Оставьте пустым и блок попадёт в конец');
define('_BLOCK_GROUPS', 'Доступно группам');
define('_BLOCK_GROUPS_TT', 'Для выбора нескольких групп зажмите CTRL.');
define('_BLOCK_ACTIVE', 'Активный');
define('_BLOCK_ALL', 'Во всех');
define('_BLOCK_FREE', 'Свободный');
define('_BLOCK_INDEX', 'Только на главной');
define('_BLOCK_UNSHOW', 'Отрицание отмеченных');
define('_BLOCK_FILECHOOSED', '<b>Выбран файл, редактирование контента невозможно!</b> (<u>Выберите Нет Файла и редактирование будет доступно</u>)');
define('_BLOCK_FOR_TPL', 'Для шаблона');
define('_BLOCK_DELETEFROM_TYPE', 'Удалить блоки этого типа');
define('_BLOCK_TYPE_TITLE', 'Заголовок типа');
define('_BLOCK_TYPEF_TT', 'Тип для обработки в шаблонах');
define('_BLOCK_TYPE_TITLE_TT', 'Заголовок типа отображаемый в АП');
define('_BLOCK_ADD_TYPE', 'Добавить тип блока');
define('_BLOCK_EDIT_TYPE', 'Редактировать тип блока');
define('_BLOCK_TYPE_DEL', 'Вы действительно хотите удалить');
define('_BLOCK_STANDART', 'Настройка стандартных блоков');

define('_LOG_LOG', 'Логи системы');
define('_LOG_OK_COM', 'Действие успешно выполнено');
define('_LOG_OK_CLEAR', 'Логи ошибок успешно очищены! <a href="javascript:history.go(-1)" title="Назад">Вернуться назад</a>');
define('_LOG_NAME', 'Логи безопасности');
define('_LOG_ERROR', 'ошибок');
define('_LOG_CLEAR', 'Очистить логи');
define('_LOG_EMPTY', 'Логи пусты!');

define('_SMAILE_SMAILE', 'Смайл');
define('_SMAILE_SMAILES', 'Смайлы');
define('_SMAILE_LIST', 'Список смайлов');
define('_SMAILE_ADD', 'Добавить смайл');
define('_SMAILE_TAG', 'BB тэг');
define('_SMAILE_DESC', 'Описание');
define('_SMAILE_URL', 'URL смайла');
define('_SMAILE_DEL', 'Удалить');
define('_SMAILE_FOLDER', 'Из папки');
define('_SMAILE_TITLE', 'Управление смайлами');
define('_SMAILE_INFO_1', 'Конфигурации успешно сохранены');
define('_SMAILE_INFO_2', 'Смайл успешно добавлен');
define('_SMAILE_INFO_3', 'Смайл не добавлен, т.к. не найден на сервере.');
define('_SMAILE_FOUND', 'найден');
define('_SMAILE_NOT_FOUND', 'не найден');

define('_USER_USER', 'Пользователь');
define('_USER_USERS', 'Пользователи');
define('_USER_TITLE', 'Управление пользователями');
define('_USER_NAVIGATION', 'Навигация');
define('_USER_ADD', 'Добавление пользователя');
define('_USER_FULL_SEARCH', 'Расширенный поиск');
define('_USER_INPUT', 'Введите имя');
define('_USER_SEARCH', 'Поиск');
define('_USER_SHORT', 'Сортировать по:');
define('_USER_ABC', 'алфавиту');
define('_USER_LAST_V', 'последний визит');
define('_USER_ID', 'id');
define('_USER_SEARCH_BY', 'Искать по:');
define('_USER_NICK', 'Ник');
define('_USER_EMAIL', 'E-Mail');
define('_USER_NAME', 'Имя');
define('_USER_PASS', 'Пароль');
define('_USER_GROUP', 'Пароль');
define('_USER_SONAME', 'Фамилия');
define('_USER_IP', 'IP адрес');
define('_USER_G_D', 'Любая');
define('_USER_BANNED', 'Забанен');
define('_BAN', 'Забанить');
define('_USER_ADD_INFO_1', 'Такой пользователь уже существует в системе');
define('_USER_ADD_INFO_2', 'Пользователь успешно добавлен!');

define('_DB_DB', 'База данных');
define('_DB_TABLE', 'Таблица');
define('_DB_TABLE_NAME', 'Название таблицы');
define('_DB_TABLE_CODE', 'Кодировка');
define('_DB_TABLE_NUMB', 'Строк');
define('_DB_TABLE_SIZE', 'Размер');
define('_DB_TABLE_DEL', 'Удаление таблицы');
define('_DB_TABLE_DELETE', 'успешно удалена.');
define('_DB_TRUNCATE', 'Очистить таблицу');
define('_DB_CLEAR', 'Очищение таблицы');
define('_DB_CLEAR_OK', 'успешно очищено.');
define('_DB_DELETE', 'Удалить таблицу');
define('_DB_CHOICE', 'Выберите таблицы');
define('_DB_ABOUT', 'Описание');
define('_DB_OP_NAME', 'Оптимизация');
define('_DB_OP_DO', 'Оптимизировать');
define('_DB_OP_TEXT', 'Вы можете произвести оптимизацию базы данных, тем самым будет сэкономлено немного места на диске, а также ускорена работа базы данных. Рекомендуется использовать данную функцию минимум один раз в неделю.');
define('_DB_RE_NAME', 'Ремонт базы данных');
define('_DB_RE_DO', 'Починить');
define('_DB_RE_TEXT', 'При неожиданной остановке MySQL сервера, во время выполнения каких-либо действий, может произойти повреждение структуры таблиц, использование этой функции поможет решить вам эту проблему.');
define('_DB_BE_NAME', 'Резервное копирование');
define('_DB_BE_DO', 'Бекап');
define('_DB_BE_TEXT', 'Для сохранения в целостности данных сайта следует время от времени делать резервные копии базы данных, при потере данных вы всегда можете вернуть из бекапа сайт.');
define('_DB_BE_COPY', 'Копии на сервере');
define('_DB_BE_NO', 'Бекапов базы данных не обнаружено!');
define('_DB_BE_RES', 'Восстановить бекап');
define('_DB_BE_DEL', 'Удалить бекап');
define('_DB_BE_ERROR', 'Выполнить бекап невозможно!');
define('_DB_BE_COM', 'Резервная копия базы данных сделана и доступна в папке: ');
define('_DB_BE_BACK', 'Вернуться>>');
define('_DB_BE_SERVER', 'Информация с сервера:');
define('_DB_BE_DOWNLOAD', 'Скачать бекап.');
define('_DB_BE_REST', 'Восстановление БД');
define('_DB_BE_REST_OK', 'База данных успешно восстановлена.');
define('_DB_BE_REST_NO', 'Не удалось восстановить базу данных!');
define('_DB_BB_NAME', 'Пересчёт BB');
define('_DB_BB_DO', 'Обновить BB');
define('_DB_BB_START', 'Начало');
define('_DB_BB_END', 'Конец');

define('_COM_COM', 'Комментарии');
define('_COM_OK', 'Действие успешно выполнено');
define('_COM_LIST', 'Список комментариев');
define('_COM_LIST_M', 'Список комментариев на модерации');
define('_COM_NO', 'Комментарии отсутствуют.');
define('_COM_ID', 'ID Комментария');
define('_COM_EDIT', 'Редактирование комментария');
define('_COM_ACT', 'Активировать комментарий?');
define('_COM_TEXT', 'Текст комментария');
define('_COM_UPDATE', 'Комментарий успешно обновлён.');
define('_COM_DELETE', 'Удалить комментарий ');

define('_CONFIGURATION', 'Конфигурации системы');
define('_CONF_INF_TH', 'Информация к размышлению');
define('_CONF_EXPAND', 'раскрыть');
define('_CONF_SUMM', 'Всего настроек');
define('_SUCCESS_SAVE', 'Параметры успешно сохранены.');
define('_ACCEPT', 'Принять');


define('_TPL_TPL', 'Шаблон');
define('_TPL_TPLS', 'Шаблоны');
define('_TPL_UPLOAD_TPL', 'Загрузить шаблон:');
define('_TPL_UPLOAD_INF', 'Выбирите файл (в формате zip) шаблона который вы хотите встроить в систему:');
define('_TPL_IN', 'Стандартный шаблон для');
define('_TPL_OUT', 'Сторонний шаблон для');
define('_TPL_LOAD', 'Скачать шаблон');
define('_TPL_DEL', 'Удалить шаблон');
define('_TPL_EDET', 'Редактировать шаблон');
define('_TPL_EDET_CSS', 'Редактировать стили');
define('_TPL_NO_CSS', 'Выберите css файл для редактирования!');
define('_TPL_EDET_CH', 'Выбор файла tpl');
define('_TPL_EDET_CSS_CH', 'Выбор файла css');
define('_TPL_FOLD_MAIN', 'Главное');
define('_TPL_FOLD_BLOG', 'Блоги');
define('_TPL_FOLD_BOARD', 'Форум');
define('_TPL_FOLD_COMM', 'Комментарии');
define('_TPL_FOLD_CONTENT', 'Страницы');
define('_TPL_FOLD_GALLERY', 'Галерея');
define('_TPL_FOLD_GUEST', 'Гостевая');
define('_TPL_FOLD_NEWS', 'Новости');
define('_TPL_FOLD_PM', 'ПМ');
define('_TPL_FOLD_PROFILE', 'Профиль');
define('_TPL_FOLD_SEARCH', 'Поиск'); 
define('_TPL_NAME_INDEX', 'Главная страница');
define('_TPL_NAME_INFO', 'Информация');
define('_TPL_NAME_PAGE', 'Навигация');
define('_TPL_NAME_SITEMAP', 'Карта сайта');
define('_TPL_NAME_TABLE', 'Таблица контента');
define('_TPL_NAME_TITLE', 'Заголовки');
define('_TPL_NAME_WARNING', 'Предупреждения');
define('_TPL_NAME_POLL', 'Голосования');
define('_TPL_NAME_FEEDBACK', 'Обратная связь');
define('_TPL_NAME_BLOCK', 'Вывод PHP блоков');
define('_TPL_NAME_MAINPAGE', 'Контент на главной');
define('_TPL_NAME_CUSTOMS', 'Вывод новостей по шаблону');
define('_TPL_NAME_BB', 'BB коды');
define('_TPL_NAME_COM', 'Комментарий');
define('_TPL_NAME_N_CAT', 'Новость в категории');
define('_TPL_NAME_N_VIEW', 'Просмотр новости');
define('_TPL_NAME_N_MAIN', 'Новость на главной');
define('_TPL_NAME_N_ADD', 'Добавить новость');
define('_TPL_NAME_CSS_ENG', 'Стиль системы');
define('_TPL_NAME_CSS_THM', 'Стиль шаблона');
define('_TPL_INFO_0', 'Шаблон успешно удалён.');
define('_TPL_INFO_1', 'Невозможно удалить шаблон. Возможно он выбран, как основной.');
define('_TPL_INFO_2', 'Шаблон успешно выбран!');
define('_TPL_INFO_3', 'Шаблон успешно загружен на сайт!');
define('_TPL_INFO_4', 'Не удалось загрузить шаблон, проверьте правильность архива.');
define('_TPL_INFO_5', 'Шаблон успешно сохранен.');
define('_TPL_INFO_6', 'Стиль успешно сохранен.');

define('_CONFIG_SEO', 'Настройки SEO');
define('_CONFIG_KEYWORDS', 'Keywords модуля');
define('_CONFIG_SEO_DESC', 'Для SEO оптимизации сайта');
define('_CONFIG_DESC', 'Description модуля');
define('_CONFIG_TOPBAR', 'Настройки топбара');
define('_CONFIG_TOPBAR_SWITCH', 'Настройки топбара');
define('_CONFIG_TOPBAR_SWITCH_DESC', 'Настройки топбара');
define('_CONFIG_TOPBAR_URL_1', 'Настройки топбара');
define('_CONFIG_TOPBAR_URL_2', 'Настройки топбара');
define('_CONFIG_TOPBAR_URL_3', 'Настройки топбара');
define('_CONFIG_TOPBAR_URL_4', 'Настройки топбара');
define('_CONFIG_TOPBAR_URL_DESC', 'Настройки топбара');


define('_SEARCH_ERROR_0', 'Для поиска необходимо ввести ключевое слово!');
define('_SEARCH_ERROR_1', 'Поиск по данному запросу не дал результатов!');
define('_SEARCH_REF', 'перейти');

define('_AJAX_LOAD', 'Идёт загрузка информации с сервера...');
define('_AJAX_RELOAD', 'Обновить');
define('_AJAX_INFO', 'Информация');
define('_AJAX_COMPL', 'Данные успешно обновлены!');

define('_APLOGIN_LINE_1', 'Управление пользователями');
define('_APLOGIN_LINE_2', 'Управление материалами');
define('_APLOGIN_LINE_3', 'Управление комметариями');
define('_APLOGIN_LINE_4', 'Управление шаблонами');

define('_MODULE_MODULE', 'Управление модулями');
define('_MODULE_LIST_INSTALL', 'Список установленных модулей');
define('_MODULE_AP', 'Управление');
define('_MODULE_DELETE_TITLE', 'Удалить модуль - [mod]?');
define('_MODULE_DELETE_TEXT', 'Вы действительно хотите удалить модуль "[mod]"? Все относящейся к этому модулю файлы, категории и записи также будут удалены!');
define('_MODULE_ACTIVATE_TITLE', 'Активировать модуль - [mod]?');
define('_MODULE_ACTIVATE_TEXT', 'Вы действительно хотите удалить модуль "[mod]"? Все относящейся к этому модулю файлы, категории и записи также будут удалены!');
define('_MODULE_DEACTIVATE_TITLE', 'Деактивировать модуль - [mod]?');
define('_MODULE_DEACTIVATE_TEXT', 'Вы действительно хотите деактивировать модуль "[mod]"? Модуль станет недоступен как и в пользовательской части, так и панеле управления!');
define('_MODULE_DEACTIVATE', 'Деактивировать модуль');
define('_MODULE_REIVATE', 'Де/Активировать');
define('_MODULE_INFO', 'Действия успешно выполнены!');
define('_MODULE_ACTIVATE', 'Активировать модуль');
define('_MODULE_LIST_EMPTY', 'Установленные модули отсутствуют. Это явный сбой в системе. Обратитесь в службу поддержки.');
define('_MODULE_LIST_EMPTY_HELP', 'Служба поддержки');
define('_MODULE_SERVER', 'Поиск модулей');
define('_MODULE_DIRW', 'Директория [dir] недоступна для записи, установка модулей может быть некорректной. Установите права 777 на данную папку');
define('_MODULE_CATALOG', 'Каталог модулей');
define('_MODULE_NO_CONNECTION', 'Соединение с центром не установлено!');
define('_MODULE_UPLOAD', 'Загрузка модулей');
define('_MODULE_UPLOAD_URL', 'Загрузить пакет с модулем через ссылку:');
define('_MODULE_UPLOAD_ATTATION', 'Внимание! Если вы не уверены в содержании данного архива(не представлен доверенными лицами), то воздержитесь от установки, т.к. это может повлечь необратимые последствия!');
define('_MODULE_INSTALL', 'Установить модуль');
define('_MODULE_NO_ARCHIVE', 'Архив не соответсвует стандарту!');
define('_MODULE_INSTALL_ERROR', 'Произошла ошибка при установке модуля. Приносим свои извенения за неудобства.');
define('_MODULE_INSTALL_BD', 'Необходимые запросы выполнены в базу данных');
define('_MODULE_INSTALL_COMPL', 'Модуль успешно установлен на сайт.');
define('_MODULE_DELETE', 'Удаление модуля');
define('_MODULE_DELETE_COMPL', 'Действие выполнено! Модуль успешно удалён с сайта.');